apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHVxdXF1c3J3
  CLOUDINARY_KEY: Njc1NjE5NDU3NDQxNzc0
  CLOUDINARY_SECRET: TDduN3BGQ0ZMYURkX0I1X2ktczhWR2Y2WkM0
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lhM1Z6ZFcxaE1qQXlOaUlzSW1FaU9pSmpiVzF5YW5Zek1tSXdjMll6TW05emFUbHBNWEUyZFhka0luMC5XQjRSUkFuVW8tdmxnOXVuY29CbHVn
  DB_URL: bW9uZ29kYitzcnY6Ly9teXVzZXI6S3VzdW1hQDEyQGNsdXN0ZXIxLmh5bWJ4czkubW9uZ29kYi5uZXQvP2FwcE5hbWU9Q2x1c3RlcjE=
